spring:

  profiles:
    active: prod

  application:
    name: base-template

  redis:
    database: 0
    #连接池配置
    pool:
      size: 10
      maxIdleSize: 16
      minIdleSize: 8
    #单机配置
    single:
      address: localhost:6379
      password: password
    #哨兵配置
    sentinel:
      password: redispassword
      master: mymaster
      nodes: 172.26.180.22:7000,172.26.180.20:7000,172.26.180.15:7000
    #集群配置
    cluster:
      nodes:
#      - app-rds-cluster-0.app-rds-cluster.default.svc.cluster.local:6379
#      - app-rds-cluster-1.app-rds-cluster.default.svc.cluster.local:6379
#      - app-rds-cluster-2.app-rds-cluster.default.svc.cluster.local:6379
#      - app-rds-cluster-3.app-rds-cluster.default.svc.cluster.local:6379
#      - app-rds-cluster-4.app-rds-cluster.default.svc.cluster.local:6379
#      - app-rds-cluster-5.app-rds-cluster.default.svc.cluster.local:6379

#全局使用关联nacos的负载均衡规则 如果为false则全局使用轮询规则
ribbon:
  nacosBalancer: false

# feign全局默认配置
feign:
  client:
    config:
      # 全局配置
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  okhttp:
    enabled: false
  httpclient:
    enabled: false
  hystrix:
    enabled: false